import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useBusiness } from '../context/BusinessContext';
import { 
  Printer, 
  ShieldCheck, 
  ArrowLeft,
  Calendar,
  CheckCircle2,
  FileCheck,
  Building2,
  User,
  DollarSign,
  PieChart
} from 'lucide-react';

export default function ReportActionPlan() {
  const location = useLocation();
  const navigate = useNavigate();
  const businessCtx = useBusiness();

  // Priority: 1. Router location state -> 2. Active BusinessContext state
  const liveData = location.state || {};

  const businessType = liveData?.businessDetails?.businessType || businessCtx.businessType || 'Dairy Farming & Milk Chilling Unit';
  const village = businessCtx.location?.locality || 'Phulpur';
  const district = businessCtx.location?.city || 'Pindra, Varanasi';
  const stateName = businessCtx.location?.state || 'Uttar Pradesh';

  const score = liveData?.feasibility?.feasibility_score ?? businessCtx.feasibility?.feasibility_score ?? 88.94;
  const totalCost = liveData?.finance?.totalProjectCost ?? businessCtx.finance?.totalProjectCost ?? 1000000;
  const loanAmount = liveData?.finance?.loanAmount ?? businessCtx.finance?.loanAmount ?? 900000;
  const marginCapital = liveData?.finance?.marginCapital ?? businessCtx.finance?.marginCapital ?? 100000;

  const capexAmount = totalCost * 0.75;
  const opexAmount = totalCost * 0.25;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-slate-50 p-6 md:p-10">
      <div className="max-w-7xl mx-auto space-y-8 print:p-0 print:bg-white print:max-w-none">
        
        {/* Top Navigation & Print Actions */}
        <div className="flex justify-between items-center print:hidden">
          <button
            type="button"
            onClick={() => navigate('/advisor', { state: liveData })}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-300 rounded-xl text-slate-700 font-medium text-sm hover:bg-slate-100 transition shadow-sm"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Phase 6
          </button>
          
          <button
            type="button"
            onClick={handlePrint}
            className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 text-white font-semibold text-sm rounded-xl hover:bg-blue-700 transition shadow-md"
          >
            <Printer className="w-4 h-4" /> Print / Download Bank DPR (PDF)
          </button>
        </div>

        {/* Main Bank-Ready Detailed Project Report (DPR) */}
        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm space-y-8 print:border-none print:shadow-none print:p-0">
          
          {/* Header Banner with Reference Code */}
          <div className="border-b border-slate-200 pb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <span className="px-3 py-1 bg-blue-100 text-blue-700 font-extrabold text-xs rounded-full uppercase tracking-wider">
                  Phase 7: Institutional DPR
                </span>
                <span className="px-2.5 py-1 bg-slate-100 text-slate-600 font-mono text-xs font-bold rounded-md border border-slate-200">
                  DPR Ref: VM/2026/VAR/31711
                </span>
              </div>
              <h1 className="text-3xl font-extrabold text-slate-900 mt-2">
                {businessType} — Bank DPR Master Plan
              </h1>
              <p className="text-xs text-slate-500 mt-1">
                Generated by VYAPARMITRA Decision Support & Financial Structuring Engine
              </p>
            </div>

            <div className="text-right self-start md:self-auto">
              <span className="text-xs font-bold text-slate-400 uppercase">Appraisal Status</span>
              <p className="text-emerald-600 font-extrabold text-sm flex items-center justify-end gap-1 mt-1">
                <ShieldCheck className="w-4 h-4" /> Bank & SCA Credit Ready
              </p>
            </div>
          </div>

          {/* Section 1: Enterprise & Geographic Profile */}
          <div className="space-y-3">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider bg-slate-100 p-2.5 rounded-lg border border-slate-200">
              1. Enterprise & Geographic Profile
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs p-2">
              <div>
                <p className="text-slate-400 font-medium">Proposed Activity:</p>
                <p className="font-bold text-slate-900 mt-0.5">{businessType}</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium">Gram Panchayat / Village:</p>
                <p className="font-bold text-slate-900 mt-0.5">{village}</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium">Block & District:</p>
                <p className="font-bold text-slate-900 mt-0.5">{district}</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium">State:</p>
                <p className="font-bold text-slate-900 mt-0.5">{stateName}</p>
              </div>
            </div>
          </div>

          {/* Section 2: Beneficiary Qualification & Margin Equity */}
          <div className="space-y-3">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider bg-slate-100 p-2.5 rounded-lg border border-slate-200">
              2. Beneficiary Qualification & Margin Equity
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs p-2">
              <div>
                <p className="text-slate-400 font-medium">Beneficiary Category:</p>
                <p className="font-bold text-slate-900 mt-0.5">SC Community (NSFDC Eligible)</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium">Gender & Income Bracket:</p>
                <p className="font-bold text-slate-900 mt-0.5">Male | ₹1,80,000/yr</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium">Prior Skill Training:</p>
                <p className="font-bold text-slate-900 mt-0.5">PM-DAKSH Certified</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium">Own Cash Margin (10%):</p>
                <p className="font-bold text-emerald-600 mt-0.5">₹{marginCapital.toLocaleString()}</p>
              </div>
            </div>
          </div>

          {/* Section 3: Financial Structuring & SCA Concessional Credit Appraisal */}
          <div className="space-y-3">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider bg-slate-100 p-2.5 rounded-lg border border-slate-200">
              3. Financial Structuring & SCA Concessional Credit Appraisal
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 bg-slate-50 p-4 rounded-xl border border-slate-200 text-xs">
              <div>
                <p className="text-slate-400 font-medium uppercase">Total Project Cost:</p>
                <p className="text-xl font-black text-slate-900 mt-0.5">₹{totalCost.toLocaleString()}</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium uppercase">Concessional Loan (90%):</p>
                <p className="text-xl font-black text-emerald-600 mt-0.5">₹{loanAmount.toLocaleString()}</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium uppercase">Approved Scheme:</p>
                <p className="text-xs font-bold text-slate-900 mt-1">MoSJE General Term Loan Scheme</p>
              </div>
              <div>
                <p className="text-slate-400 font-medium uppercase">Interest & Tenure:</p>
                <p className="text-xs font-bold text-slate-900 mt-1">8% p.a. | 7 Years</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2 text-xs">
              <div className="p-3 bg-white rounded-xl border border-slate-200 text-center">
                <p className="text-slate-400 font-medium uppercase text-[10px]">Gestation Moratorium</p>
                <p className="font-extrabold text-slate-900 mt-0.5">6 Months (Principal Holiday)</p>
              </div>
              <div className="p-3 bg-white rounded-xl border border-slate-200 text-center">
                <p className="text-slate-400 font-medium uppercase text-[10px]">Quarterly Installment</p>
                <p className="font-extrabold text-slate-900 mt-0.5">₹44,729</p>
              </div>
              <div className="p-3 bg-white rounded-xl border border-slate-200 text-center">
                <p className="text-slate-400 font-medium uppercase text-[10px]">Debt Service Ratio (DSCR)</p>
                <p className="font-extrabold text-emerald-600 mt-0.5">2.51x (Healthy)</p>
              </div>
            </div>
          </div>

          {/* Section 4: Project Cost Allocation Table */}
          <div className="space-y-3">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider bg-slate-100 p-2.5 rounded-lg border border-slate-200">
              4. Project Cost Allocation (Capex vs Working Capital)
            </h2>
            
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="border-b border-slate-200 text-slate-400 uppercase font-bold tracking-wider bg-slate-50">
                    <th className="p-3">Cost Head</th>
                    <th className="p-3">Description / Machinery</th>
                    <th className="p-3">Amount (₹)</th>
                    <th className="p-3">% of Total</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-slate-700">
                  <tr>
                    <td className="p-3 font-bold text-slate-900">Capital Expenditure (CapEx)</td>
                    <td className="p-3">Bulk Milk Chilling Tank (500L), Generator set, Shed electrification & cans</td>
                    <td className="p-3 font-semibold text-slate-900">₹{capexAmount.toLocaleString()}</td>
                    <td className="p-3 font-bold text-blue-600">75%</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-bold text-slate-900">Working Capital Reserve (OpEx)</td>
                    <td className="p-3">Raw milk procurement advance, utility buffer, packaging & initial staff wages</td>
                    <td className="p-3 font-semibold text-slate-900">₹{opexAmount.toLocaleString()}</td>
                    <td className="p-3 font-bold text-blue-600">25%</td>
                  </tr>
                  <tr className="bg-slate-50 font-black text-slate-900">
                    <td className="p-3">Total Project Outlay</td>
                    <td className="p-3">Complete 10/90 Financed Micro-Enterprise Unit</td>
                    <td className="p-3 text-emerald-600">₹{totalCost.toLocaleString()}</td>
                    <td className="p-3">100%</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 5: 90-Day Implementation Roadmap */}
          <div className="space-y-4">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider bg-slate-100 p-2.5 rounded-lg border border-slate-200 flex items-center gap-2">
              <Calendar className="w-4 h-4 text-blue-600" /> 5. 90-Day Implementation Roadmap
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
              <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="px-2 py-0.5 bg-blue-600 text-white font-extrabold text-[10px] rounded uppercase">Days 1–30</span>
                <h3 className="font-bold text-slate-900 pt-1">Subsidies & Compliance</h3>
                <p className="text-slate-600">Submit margin capital proof to channel agency for subsidy clearance. Obtain trade/FSSAI licensing and open current bank account.</p>
              </div>

              <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="px-2 py-0.5 bg-blue-600 text-white font-extrabold text-[10px] rounded uppercase">Days 31–60</span>
                <h3 className="font-bold text-slate-900 pt-1">Procurement & Site Setup</h3>
                <p className="text-slate-600">Procure primary machinery and chilling units via loan disbursement. Establish supply linkages in target catchment zone.</p>
              </div>

              <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="px-2 py-0.5 bg-blue-600 text-white font-extrabold text-[10px] rounded uppercase">Days 61–90</span>
                <h3 className="font-bold text-slate-900 pt-1">Operations & Commercial Launch</h3>
                <p className="text-slate-600">Launch commercial operations, commence quarterly moratorium interest servicing, and track working capital.</p>
              </div>
            </div>
          </div>

          {/* Immediate Action Checklist */}
          <div className="pt-2 space-y-3">
            <h3 className="font-bold text-slate-900 text-xs flex items-center gap-2">
              <FileCheck className="w-4 h-4 text-emerald-600" /> Immediate Checklist
            </h3>
            <ul className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-slate-700">
              <li className="flex items-center gap-2 bg-emerald-50 p-3 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0" />
                <span>Verify MoSJE / National Scheme eligibility document</span>
              </li>
              <li className="flex items-center gap-2 bg-emerald-50 p-3 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0" />
                <span>Attach project cost sheet & registration docs to Bank Application</span>
              </li>
            </ul>
          </div>

        </div>

      </div>
    </div>
  );
}